### ISSUE TITLE
Potential bug: Huge memory consumption in KID

### ISSUE THREAD

**Issue by zakajd** [photosynthesis-team/piq#214]
**Describe the bug**
As mentioned by @bes-dev in ODS chat, when using KID with big size of features, it consumes a lot of memory.
Need to investigate this further and fix, if possible.

**Expected behavior**
Limited memory use for reasonably sized inputs.

**How to reproduce**
To be updated ...

**Comment by chenquan-hdu** [comment]
Hi,

I also want to calculate KID, but I don't quite understand the use of 'Dataloader', can you share your use method?

Thank you.

**Comment by zakajd** [comment]
Hi @chenquan-hdu 

As written in the docstring for compute_feats method, we expect dataloader to return a dictionary with key images in it.
Standart DataLoader returns tuples of (image, label), so here is quick hack to make it work:

```python
class DictDataLoader(DataLoader):
    def __next__(self):
        data = super().__next__(self)
        return {'images': data[0], 'labels': data[1]}
first_dl, second_dl = DictDataLoader('/content/test'), DictDataLoader('/content/generate')
```
Modify this example accordingly if you have different DataLoader structure

**Comment by chenquan-hdu** [comment]
Thank you! I will try.

**Comment by chenquan-hdu** [comment]
Hi，

There are still some problems with the code, I hope you can help me.

Thank you.

`def is_image_file(filename):
    return any(filename.endswith(extension) for extension in [".png", ".jpg"])

class DatasetFromFolder(data.Dataset):
    def __init__(self, image_dir):
        super(DatasetFromFolder, self).__init__()
        self.img_path = image_dir
        self.img_filenames_list = [x for x in listdir(image_dir) if is_image_file(x)]

    def __getitem__(self, index):
        img_number = (self.img_filenames_list[index]).split('.')[0]
        img = cv2.imread(self.img_path + img_number + '.png')
        img = ToTensor()(img)
        return img

    def __len__(self):
        return len(self.img_filenames_list)

class DictDataLoader(DataLoader):
    def __next__(self):
        data = super().__next__(self)
        return {'images': data[0]}

first_dl, second_dl = DictDataLoader('Val100/val_images_v10_level3_91113_png/'),DictDataLoader('Val100/val_images_yang_png/')
fid_metric = FID()
first_feats = fid_metric.compute_feats(first_dl)
second_feats = fid_metric.compute_feats(second_dl)
fid: torch.Tensor = fid_metric(first_feats, second_feats)
`


There are still some errors.

`C:\software\Anaconda3\envs\SRCNN\lib\site-packages\torchvision\models\inception.py:77: FutureWarning: The default weight initialization of inception_v3 will be changed in future releases of torchvision. If you wish to keep the old behavior (which leads to long initialization times due to scipy/scipy#11299), please set init_weights=True.
  ' due to scipy/scipy#11299), please set init_weights=True.', FutureWarning)
Traceback (most recent call last):
  File "D:/project/AIM2019_self/calcu_KID.py", line 38, in <module>
    first_feats = fid_metric.compute_feats(first_dl)
  File "C:\software\Anaconda3\envs\SRCNN\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "C:\software\Anaconda3\envs\SRCNN\lib\site-packages\piq-0.5.5-py3.6.egg\piq\base.py", line 44, in compute_feats
TypeError: list indices must be integers or slices, not str`

**Comment by chenquan-hdu** [comment]
Hi,

There are some mistakes, I really hope you can help me.

Thank you.

```
def is_image_file(filename):
    return any(filename.endswith(extension) for extension in [".png", ".jpg"])

class DatasetFromFolder(data.Dataset):
    def __init__(self, image_dir):
        super(DatasetFromFolder, self).__init__()
        self.img_path = image_dir
        self.img_filenames_list = [x for x in listdir(image_dir) if is_image_file(x)]

    def __getitem__(self, index):
        img_number = (self.img_filenames_list[index]).split('.')[0]
        img = cv2.imread(self.img_path + img_number + '.png')
        img = ToTensor()(img)
        return img

    def __len__(self):
        return len(self.img_filenames_list)

class DictDataLoader(DataLoader):
    def __next__(self):
        data = super().__next__(self)
        return {'images': data[0]}

first_dl, second_dl = DictDataLoader('Val100/val_images_v10_level3_png'), DictDataLoader('Val100/val_images_yang_png')
fid_metric = FID()
first_feats = fid_metric.compute_feats(first_dl)
second_feats = fid_metric.compute_feats(second_dl)
fid: torch.Tensor = fid_metric(first_feats, second_feats)
```

ERROR
```
C:\software\Anaconda3\envs\SRCNN\lib\site-packages\torchvision\models\inception.py:77: FutureWarning: The default weight initialization of inception_v3 will be changed in future releases of torchvision. If you wish to keep the old behavior (which leads to long initialization times due to scipy/scipy#11299), please set init_weights=True.
  ' due to scipy/scipy#11299), please set init_weights=True.', FutureWarning)
Traceback (most recent call last):
  File "D:/project/AIM2019_self/calcu_KID.py", line 38, in <module>
    first_feats = fid_metric.compute_feats(first_dl)
  File "C:\software\Anaconda3\envs\SRCNN\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "C:\software\Anaconda3\envs\SRCNN\lib\site-packages\piq-0.5.5-py3.6.egg\piq\base.py", line 44, in compute_feats
TypeError: list indices must be integers or slices, not str
```

**Comment by zakajd** [comment]
You are iterating over letters in `'Val100/val_images_v10_level3_png'` string, not actual images 🤦🏼 
Use `DictDataLoader(DatasetFromFolder(path))` syntax.

**Comment by chenquan-hdu** [comment]
Yes, I tried to write that, but it was still wrong. 

```
first_dl, second_dl = DictDataLoader(DatasetFromFolder(Val100/val_images_yang_png/')),DictDataLoader(DatasetFromFolder('Val100/val_images_yang_png/'))
fid_metric = FID()
```

I think the above script is equivalent to `DictDataLoader(dataset=DatasetFromFolder(path))`, but it still has errors.


ERROR
```
C:\software\Anaconda3\envs\SRCNN\lib\site-packages\torchvision\models\inception.py:77: FutureWarning: The default weight initialization of inception_v3 will be changed in future releases of torchvision. If you wish to keep the old behavior (which leads to long initialization times due to scipy/scipy#11299), please set init_weights=True.
  ' due to scipy/scipy#11299), please set init_weights=True.', FutureWarning)
Traceback (most recent call last):
  File "D:/project/AIM2019_self/calcu_KID.py", line 36, in <module>
    first_feats = fid_metric.compute_feats(first_dl)
  File "C:\software\Anaconda3\envs\SRCNN\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "C:\software\Anaconda3\envs\SRCNN\lib\site-packages\piq-0.5.5-py3.6.egg\piq\base.py", line 44, in compute_feats
IndexError: too many indices for tensor of dimension 4
```

**Comment by chenquan-hdu** [comment]
Hi，
Thanks for your help, the ‘FID program’ can run normally.

But when I changed FID to KID, the result was -0.0024. Why is it negative?
The Dataloader remains the same as when calculating FID.

```
kid_metric = KID()
first_feats = kid_metric.compute_feats(first_dl)
second_feats = kid_metric.compute_feats(second_dl)
fid: torch.Tensor = kid_metric(second_feats, first_feats)
print(fid) 
```

**Comment by snk4tr** [comment]
It seems like the initial request was related to the following behavior:
1. In order to compute **FID/KID** metric, features need to be extracted from the initial images;
2. Features are better be extracted on GPU because in this case the process requires reasonable execution time;
3. For that, quite some GPU memory needs to be allocated **before** computation of the metrics.

For example, to compute features of size `2048` on 10k images, the code would need ~14Gb of video memory to allocate `[10000, 2048]` feature maps tensor. 

**Solution**: introduce a batch-wise features and metrics computation to make execution with low-memory GPUs possible.
