### ISSUE TITLE
PieAPP with stride=32 requests 10TB of ram.

### ISSUE THREAD

**Issue by RashiqAzhan** [photosynthesis-team/piq#252]
**Describe the bug**
`piq.PieApp` requests 10TB of ram. I'm not aware of any consumer-grade hardware supporting as such. Please advise.

Code used:
```python
import torch
import piq
from skimage.io import imread

@torch.no_grad()
def main():
   pieapp_loss: torch.Tensor = piq.PieAPP(reduction='none', stride=32)(x, y)
   print(f"PieAPP loss: {pieapp_loss.item():0.4f}")

if __name__ == '__main__':
    main()
```

Terminal Output:
```python
Traceback (most recent call last):
  File "...\.venv\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-0a75bdc18eb8>", line 1, in <module>
    runfile('.../image_analysis_sewar.py', wdir='...')
  File "...\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "...\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File ".../image_analysis_sewar.py", line 172, in <module>
    main()
  File ".../image_analysis_sewar.py", line 169, in main
    piq_image_analysis(cover_image_path, stego_image_path)
  File "...\.venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File ".../image_analysis_sewar.py", line 132, in piq_image_analysis
    pieapp_loss: torch.Tensor = piq.PieAPP(reduction='none', stride=32)(cover_image, stego_image)
  File "...\.venv\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "...\.venv\lib\site-packages\piq\pieapp.py", line 169, in forward
    prediction_features, prediction_weights = self.get_features(prediction)
  File "...\.venv\lib\site-packages\piq\pieapp.py", line 204, in get_features
    features, weights = self.model(x_patches)
  File "...\.venv\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "...\.venv\lib\site-packages\piq\pieapp.py", line 70, in forward
    x3 = F.relu(self.conv3(self.pool(F.relu(self.conv2(F.relu(self.conv1(x)))))))
  File "...\.venv\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "...\.venv\lib\site-packages\torch\nn\modules\conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "...\.venv\lib\site-packages\torch\nn\modules\conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:75] data. DefaultCPUAllocator: not enough memory: you tried to allocate 11003756544 bytes. Buy new RAM!
```

**Comment by zakajd** [comment]
Hi!
1. What’s the size of x and y tensors?
2. Have you tried using bigger stride? 64, 128?

High memory consumption of PieAPP is a known problem because under the hood it splits the image into small patches of 64x64 and then averages their predictions. Original implementation deals with by inferencing images one by one instead of batch computation, but that’s much slower.  

In my experience having bigger stride lead to similar performance, especially for big images.

**Comment by RashiqAzhan** [comment]
Apologies for not including that information.
5120 x 2160 px.
I have tried values as high as 64 but it didn't seem to work; however, 128 seems to be working Thank you for suggesting as such. I'm not sure why I didn't try using higher values on my own accord.

Can you recommend to me what stride values I should use for a 400mp photo since that will be the final picture I will be using PieAPP for?

Side Note. I got a warning.
```python
...\.venv\lib\site-packages\piq\perceptual.py:139: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.weights = [torch.tensor(w) for w in weights]
```

**Comment by zakajd** [comment]
I don't understand the point of running perceptual metrics on such resolutions, as they are usually trained / tuned on a much slower ones and thus can't efficiently utilise learned feature representations.

My suggestion would be to downsize the images significantly, say to 1024 pixels shortest size and run dense evaluation (with stride=32 or 64), rather than using an enormous stride to fit into memory requirements.

> Side Note. I got a warning.

Thanks for noticing, this warning appeared after upgrade to torch 1.5 or 1.6, will address this later.

**Comment by RashiqAzhan** [comment]
Thank you. I shall do as advised.
